title: RPLCN24 Site
description: Prototipe situs web kelas RPLCN24 yang dipergunakan untuk kemudahan organisasi kelas serta sebagai situs web repositori dan memorial kelas.
baseurl: ""
url: "https://rplcn24.classs.my.id/"